name = "eoc"
version = "1.0.0"
# target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
nibble = ">= 1.1.3 and < 2.0.0"
lustre = ">= 5.3.4 and < 6.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_community_colour = ">= 2.0.2 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.9.2 and < 2.0.0"
